package handler

import (
	"context"
	"io"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"

	"github.com/artmuc/fatyai/internal/middleware"
)

// templComponent is the interface generated by templ for all components.
type templComponent interface {
	Render(ctx context.Context, w io.Writer) error
}

// renderTempl writes a templ component to the Gin response.
func renderTempl(c *gin.Context, component templComponent) {
	c.Header("Content-Type", "text/html; charset=utf-8")
	if err := component.Render(c.Request.Context(), c.Writer); err != nil {
		c.Status(http.StatusInternalServerError)
	}
}

// isHTMX reports whether the request was made by HTMX.
func isHTMX(c *gin.Context) bool {
	return c.GetHeader("HX-Request") == "true"
}

// sessionUserID returns the authenticated user's ID from the Gin context.
// The value is set by middleware.RequireAuth before any protected handler runs.
func sessionUserID(c *gin.Context) string {
	if v, exists := c.Get(middleware.SessionUserKey); exists {
		if id, ok := v.(string); ok {
			return id
		}
	}
	return ""
}

// dateFromQuery parses ?date=YYYY-MM-DD in the timezone from the X-Timezone header,
// falling back to UTC when the header is absent or invalid.
func dateFromQuery(c *gin.Context) time.Time {
	loc := time.UTC
	if tz := c.GetHeader("X-Timezone"); tz != "" {
		if l, err := time.LoadLocation(tz); err == nil {
			loc = l
		}
	}
	raw := c.Query("date")
	if raw == "" {
		return time.Now().In(loc)
	}
	t, err := time.ParseInLocation("2006-01-02", raw, loc)
	if err != nil {
		return time.Now().In(loc)
	}
	return t
}
