// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "time"

func ActivityForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"py-3\"><form hx-post=\"/activities\" hx-target=\"#activity-list\" hx-swap=\"afterbegin\" hx-on::after-request=\"document.getElementById('add-activity-form').innerHTML=''\" class=\"space-y-3 bg-gray-50 rounded-xl p-4\"><input type=\"text\" name=\"activity_type\" placeholder=\"np. bieganie, siłownia, rower\" required class=\"w-full border border-gray-300 rounded-xl px-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-green-500\"><div class=\"grid grid-cols-2 gap-3\"><div><label class=\"block text-xs text-gray-500 mb-1\">Czas (min)</label> <input type=\"number\" name=\"duration_min\" placeholder=\"30\" min=\"1\" required class=\"w-full border border-gray-300 rounded-xl px-3 py-2 text-sm\"></div><div><label class=\"block text-xs text-gray-500 mb-1\">Spalone kcal</label> <input type=\"number\" name=\"calories_burned\" placeholder=\"200\" step=\"1\" class=\"w-full border border-gray-300 rounded-xl px-3 py-2 text-sm\"></div></div><div><label class=\"block text-xs text-gray-500 mb-1\">Intensywność</label> <select name=\"intensity\" class=\"w-full border border-gray-300 rounded-xl px-3 py-2 text-sm\"><option value=\"low\">Niska</option> <option value=\"medium\" selected>Średnia</option> <option value=\"high\">Wysoka</option></select></div><input type=\"datetime-local\" name=\"logged_at\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(time.Now().Format("2006-01-02T15:04"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/partials/activity_form.templ`, Line: 36, Col: 94}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"w-full border border-gray-300 rounded-xl px-3 py-2 text-sm\"><div class=\"flex gap-2\"><button type=\"submit\" class=\"flex-1 bg-green-500 text-white font-semibold rounded-xl py-2 text-sm hover:bg-green-600\">Zapisz</button> <button type=\"button\" onclick=\"document.getElementById('add-activity-form').innerHTML=''\" class=\"flex-1 bg-gray-100 text-gray-600 font-semibold rounded-xl py-2 text-sm hover:bg-gray-200\">Anuluj</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
